Fix Jinja2 and MarkupSafe version issues (#424)
* fix(requirements): limit Jinja2 version to latest `2.x`

This should fix `tannerweb` issues `AttributeError: module 'jinja2' has no attribute 'contextfunction'`

* fix(requirements): limit `MarkupSafe` version to `2.0.x`

Required by `Jinja2` version `2.x`